name: Run Compliance Notify Script

# run it weekly
on: workflow_dispatch
#   schedule:
#     - cron: "0 8 * * 1"  # Also adjusted MON to 1 to adhere to cron syntax

env:
    GMAIL_PASSKEY: ${{ secrets.GMAIL_PASSKEY }}

jobs:
  build-linux:
    runs-on: macos-latest  # Corrected to macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'  # Consider using '3.11' to automatically use the latest 3.11.x version

      - name: Install dependencies and run script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python compliance_notify.py


            
