name: Run Compliance Notify Script

# run it weekly
on: workflow_dispatch
  # schedule:
  #   - cron: "05 08 * * 1" 

env:
    GMAIL_PASSKEY: ${{ secrets.MTC_GMAIL_PASSKEY }}

jobs:
  build-linux:
    runs-on: macos-latest  # Corrected to macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Install dependencies and run script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python compliance_notify.py


            
